sudo: false
language: node_js
node_js:
- '5'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_deploy:
  - rm -rf package.json tools test src docs
  - mv build/* ./
  - rm -rf build
  - ls
deploy:
  provider: heroku
  api_key:
    secure: DoEDDMxmDkf59CLrkKY1++G2Xmig0TXxqEhQKIIuB7x2h53QrzxHDgrbTNVf2sceAdKKJlQjhvqtKoMKmXtkY2SGgBuH/vrpkCWXcaSxr1e8HWcNbyqMSmvUaYNMVvmaQRB9TNVzgMwrT+5IIKu4PNV4pyt+NFlXnSxK/j0Pv8ULuNaaux92vTJZLY9Z9VI13TVf/tVUVG0iOZ+HIlqyLjuLhWOcsp5J4wZ5LGbMCYwIxmxRH7aMY2FSQcrAotrNb/tPJ1OVD0WPMIZYruoHnjsCEbck2fjtVoUFXlA5M6rdT+gbKtir6TglikQcBZ4X3ysEurfGnz1UAqAc5vdxFkAh76USot6wrzGtMVYZj37wT9t3VV8EI+ClOlPTMgW22SLS4JDDQUQbKxQkhBJES8Eic7u3pNuxHMJHa4uZXn+nYJShQsxKtFKpUNAAkFhuXcyWcf+L9B2eqne8bVjjfPDa5a5G2oVeJe8zO4Kv9KyszOIl9POWBUfLpyWjPfJ+QWotfL0jLyi1wCcRSgzsXYj6s8nk5dixDEOg/Sfg0Q8GxL+Xle2wmFheFk6NrbjD77/neqziw00N4CApOPBIa/uaYjF3RjmrtX2zOeXJjmn5FkF3U3NdbODDIc01fCKLo284Drd57RUEP60eJScbPEMRZR03O5fI0cSGeZFMFBc=
  app: pp-heroku-test
  on:
    repo: thepechinator/pp-test-heroku
